### PR TITLE
Update command

### PR DESCRIPTION
**Pull request by nikivdev**
Previous command failed for me, only showed `--help` output.

### CODE REVIEW

**Comment by sidwebworks** [comment]
Thanks for the PR Nikita, I will updating this template with the latest wails and vite setup soon.

**Comment by nikivdev** [comment]
Btw I have an issue where in this setup, `wails.dev` doesn't produce any JS bindings. Do you know what I am doing wrong?

**Comment by nikivdev** [comment]
https://github.com/learn-anything/private is the repo

**Comment by sidwebworks** [comment]
@nikitavoloboev Give me 10 or 15mins I will clone and run your repo locally on my laptop

**Comment by sidwebworks** [comment]
@nikitavoloboev 
image

It does generate the bindings, which binding isn't being generated for you?

**Comment by nikivdev** [comment]
Ok wow, was looking at them in wrong place.

Get this issue though, I tried to use it.

```js
import { styled } from "solid-styled-components"
import Input from "./Input"
import Button from "./Button"
import { Greet } from "../../wailsjs/go/main/App"

export default function AddLink() {
  return (
    <>
      <TextContent>
        <h1>Add Link</h1>
      </TextContent>
      <Input placeholder="Title" width="378px" />
      <Input placeholder="URL" width="378px" />
      <div style={{ display: "flex", gap: "20px" }}>
        <Button
          onClick={() => {
            Greet("hello")
          }}
```

Then I do `pnpm run build`, get `wails dev` running. Then press the `Add link` button but no greeting message shows up in `wails dev` console.

**Comment by nikivdev** [comment]
Also another annoying DX thing is that the suggested import if I press return here:

image


Is: `import { Greet } from "wailsjs/go/main/App"`

Which actually breaks the build as the import is incorrect I think 🤔

**Comment by sidwebworks** [comment]
@nikitavoloboev 

> Get this issue though, I tried to use it.

```go
func (a *App) Greet(name string) string {
	return fmt.Sprintf("Hello %s, It's show time!", name) // Returns a formatted string
}
```

If you want it to show up in the wails dev console instead of getting returned as the result of the binding, do this

```go
func (a *App) Greet(name string) {
  fmt.Println("Hello %s, It's show time!", name) // Formats and prints the string to stdout
}
```

**Comment by sidwebworks** [comment]
> Which actually breaks the build as the import is incorrect I think

Right, at the moment something is messed up with the build setup IMO. Maybe something changed with the CLi of Vite or Wails.

Either ways, I will create a updated one tomorrow and will make sure to check for these DX issues

**Pull request merged**
